# Generated by Django 3.2.9 on 2021-12-03 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211203_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
