# Generated by Django 3.2.9 on 2021-12-03 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_blog_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
