# Generated by Django 3.2.9 on 2021-12-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_blog_blog_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_id',
            new_name='uuid',
        ),
    ]
