# Generated by Django 3.2.9 on 2021-12-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_blog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='user_id',
        ),
    ]
