# Generated by Django 3.2.9 on 2021-12-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_user_blog_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user_id',
            new_name='user',
        ),
    ]
